# Generated by Django 3.2.9 on 2021-11-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='manager',
            new_name='parent',
        ),
    ]
